### ISSUE TITLE
update_with_media! doesn't work when status is in UTF-8

### ISSUE THREAD

**Issue by sashazykov** [hayesdavis/grackle#31]
It works only if status doesn't contain UTF-8 characters.

```
Grackle::TwitterError => Unexpected failure making request: incompatible character encodings: UTF-8 and ASCII-8BIT

ruby-1.9.3-p448/gems/grackle-0.3.0/lib/grackle/client.rb:266:in `rescue in send_request'
ruby-1.9.3-p448/gems/grackle-0.3.0/lib/grackle/client.rb:254:in `send_request'
ruby-1.9.3-p448/gems/grackle-0.3.0/lib/grackle/client.rb:247:in `call_with_format'
```

**Comment by sashazykov** [comment]
Utf-8 works if I send request without file.
